version: 2

sources:
  - name: jaffle_shop
    description: This is a replica of the Postgres database jaffle_shop used by our app
    database: raw
    schema: jaffle_shop
    tables:
      - name: customers
        columns:
          - name: id
            tests:
              - unique
              - not_null
        description: One record per customer.
      - name: orders
        columns:
          - name: id
            tests:
              - unique
              - not_null
        description: One record per order. Includes cancelled and deleted orders.
  - name: stripe
    description: This is a replica of the Postgres database STRIPE used by our app
    database: raw
    schema: stripe
    tables:
      - name: payment
        description: Stripe Payments table
